apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sample-service-account
    namespace: default
roleRef:
  kind: Role
  name: pod-reader-role # this must match the name of the Role you want to bind to
  apiGroup: rbac.authorization.k8s.io