apiVersion: v1
kind: Pod
metadata:
  name: service-account-pod
spec:
  serviceAccountName: sample-service-account
  containers:
    - name: service-account-pod
      image: busybox
      command: [ 'sh', '-c', 'echo container started & sleep 3600' ]