apiVersion: v1 
kind: Pod 
metadata:
 name: command-demo-pod
 labels:
  app: demo-app
spec:
 containers: 
 - name: demo-app-container 
   image: busybox 
   command: ['sh', '-c']
   args: ['echo hello KCAD! & sleep 3600']
 restartPolicy: Never