apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-env-var-pod
spec:
  containers:
    - name: sample-secret-env-var-pod
      image: busybox
      command: [ 'sh', '-c', 'echo Database Password: $DATABASE_PASSWORD & sleep 3600' ]
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sample-secret
              key: databasePassword