apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-volume-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: sample-secret
  containers:
    - name: sample-secret-volume-pod
      image: busybox
      command: [ 'sh', '-c', 'echo Database Password from Volume: $(cat /var/my-secret/databasePassword) & sleep 3600' ]
      volumeMounts:
       - name: secret-volume
         mountPath: /var/my-secret