apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox
      image: radial/busyboxplus:curl
      imagePullPolicy: Always
      command: ['sh', '-c', 'echo busybox started && sleep 3600']