apiVersion: v1
kind: Pod
metadata:
  name: log-writer-reader
spec:
  containers:
    - name: log-writer
      image: busybox
      imagePullPolicy: Always
      command: ['sh', '-c', 'echo hello from log-writer container >> /var/demo/logs/hello.txt & sleep 3600']
      volumeMounts:
        - name: log-volume
          mountPath: /var/demo/logs
    - name: log-reader
      image: busybox
      imagePullPolicy: Always
      command: ['sh', '-c', 'sleep 10 && cat /var/demo/logs/hello.txt & sleep 3600']
      volumeMounts:
        - name: log-volume
          mountPath: /var/demo/logs
  volumes:
    - name: log-volume