apiVersion: v1
kind: Pod
metadata:
  name: fruit-service
spec:
  containers:
    - name: fruit-service
      image: linuxacademycontent/legacy-fruit-service:1
      imagePullPolicy: Always
    - name: haproxy
      image: haproxy:1.7
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-map-volume
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
  volumes:
    - name: config-map-volume
      configMap:
         name: ha-proxy-config-map