apiVersion: v1
kind: Pod
metadata:
 name: config-map-pod-volume-demo
 labels:
  app: demo-app
spec:
 containers: 
 - name: demo-app-container 
   image: busybox 
   command: ['sh', '-c', 'echo $(cat /etc/config/greetingTwo) & sleep 3600']
   volumeMounts:
     - mountPath: /etc/config
       name: config-volume
 volumes:
   - name: config-volume
     configMap:
       name: config-map-demo