apiVersion: v1 
kind: Pod 
metadata:
 name: demo-pod
 namespace: demo-namespace
 labels:
  app: demo-app
spec:
 containers: 
 - name: demo-app-container 
   image: busybox 
   command: ['sh', '-c', 'echo hello KCAD & sleep 3600'] 
